#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCPeopleAwards;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Awards/Index.cshtml")]
    public partial class _Views_Awards_Index_cshtml : System.Web.Mvc.WebViewPage<MVCPeopleAwards.Models.ListAwardsViewModel>
    {
        public _Views_Awards_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 4 "..\..\Views\Awards\Index.cshtml"
  
    Layout = "~/Views/Awards/PartialView/LayoutAwards.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\n\n");

            
            #line 8 "..\..\Views\Awards\Index.cshtml"
 if (Request.IsAuthenticated && (HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("CandidateAdmin")))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\n            <h4");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">\n                <a");

WriteLiteral(" class=\"accordion-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" href=\"#collapseOne\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\n                    Добавление новой записи\n                </a>\n            </" +
"h4>\n        </div>\n        <div");

WriteLiteral(" id=\"collapseOne\"");

WriteLiteral(" class=\"panel-collapse collapse in\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\Awards\Index.cshtml"
           Write(Html.Partial("~/Views/Awards/CreateAwardPartial.cshtml", ViewData.Model.AwardModel));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n    </div>\n");

            
            #line 24 "..\..\Views\Awards\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\n<p>\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Awards\Index.cshtml"
Write(Ajax.ActionLink("Обновить список", "Index", "Awards", new { }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "awardsList", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\n</p>\n\n<div");

WriteLiteral(" id=\"awardsList\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Awards\Index.cshtml"
Write(Html.Partial("~/Views/Awards/ListAwardsPartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\n</div>\n\n");

DefineSection("Scripts", () => {

WriteLiteral("\n\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Views\Awards\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\n\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        function OnAwardRemove(data, status, request) {
            if (data.error) {
                OnError(request, status, data.error);
                return;
            }
            var awardId = data.id;
            $('tr[data-award-id = ' + awardId + ']').remove();
        }

        function OnError(request, status, error) {
            alert(error);
        }
    </script>

");

});

        }
    }
}
#pragma warning restore 1591
