#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCPeopleAwards;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Awards/PartialView/LayoutAwards.cshtml")]
    public partial class _Views_Awards_PartialView_LayoutAwards_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Awards_PartialView_LayoutAwards_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Awards\PartialView\LayoutAwards.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\n\n<h2>");

            
            #line 5 "..\..\Views\Awards\PartialView\LayoutAwards.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\n");

            
            #line 7 "..\..\Views\Awards\PartialView\LayoutAwards.cshtml"
  
    if (Model.Error != null && Model.Error.Trim() != "")
    {

            
            #line default
            #line hidden
WriteLiteral("        <h4>");

            
            #line 10 "..\..\Views\Awards\PartialView\LayoutAwards.cshtml"
       Write(Model.Error.ToString());

            
            #line default
            #line hidden
WriteLiteral("</h4>\n");

WriteLiteral("        <hr />\n");

            
            #line 12 "..\..\Views\Awards\PartialView\LayoutAwards.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\n\n");

            
            #line 15 "..\..\Views\Awards\PartialView\LayoutAwards.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 16 "..\..\Views\Awards\PartialView\LayoutAwards.cshtml"
Write(RenderSection("Scripts", false));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
