#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCPeopleAwards;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Awards/PartialView/PhotoElement.cshtml")]
    public partial class _Views_Awards_PartialView_PhotoElement_cshtml : System.Web.Mvc.WebViewPage<MVCPeopleAwards.Models.AwardViewModel>
    {
        public _Views_Awards_PartialView_PhotoElement_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Views\Awards\PartialView\PhotoElement.cshtml"
Write(Html.LabelFor(model => model.PhotoAward, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\n    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\n        ");

WriteLiteral("\n");

            
            #line 7 "..\..\Views\Awards\PartialView\PhotoElement.cshtml"
        
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Awards\PartialView\PhotoElement.cshtml"
         if (Model.PhotoAward != null && Model.Id > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" id=\"PhotoAward\"");

WriteLiteral(" name=\"PhotoAward\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"file\"");

WriteLiteral("\n                   accept=\"image/jpg, image/png, image/jpeg\"");

WriteLiteral("\n                   data-language=\"ru\"");

WriteLiteral("\n                   data-show-upload=\"false\"");

WriteLiteral("\n                   data-show-remove=\"false\"");

WriteLiteral("\n                   data-max-file-size=\"2048\"");

WriteLiteral("\n                   data-max-file-count=\"1\"");

WriteLiteral("\n                   data-preview-file-type=\"text\"");

WriteLiteral("\n                   data-initial-preview=\"<img width=\'150\' height=\'150\' class=\'fi" +
"le-preview-image\' src=\'");

            
            #line 17 "..\..\Views\Awards\PartialView\PhotoElement.cshtml"
                                                                                                  Write(Url.Action("GetPhotoAward", "Awards", new { Model.Id }));

            
            #line default
            #line hidden
WriteLiteral("\'/>\"");

WriteLiteral(" />\n");

            
            #line 18 "..\..\Views\Awards\PartialView\PhotoElement.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" id=\"PhotoAward\"");

WriteLiteral(" name=\"PhotoAward\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"file\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-length=\"Это поле должно быть заполнено\"");

WriteLiteral("\n                   accept=\"image/jpg, image/png, image/jpeg\"");

WriteLiteral("\n                   data-language=\"ru\"");

WriteLiteral("\n                   data-show-upload=\"false\"");

WriteLiteral("\n                   data-max-file-size=\"2048\"");

WriteLiteral("\n                   data-max-file-count=\"1\"");

WriteLiteral("\n                   data-preview-file-type=\"text\"");

WriteLiteral(" />\n");

            
            #line 28 "..\..\Views\Awards\PartialView\PhotoElement.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 29 "..\..\Views\Awards\PartialView\PhotoElement.cshtml"
   Write(Html.ValidationMessageFor(model => model.PhotoAward, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n</div>");

        }
    }
}
#pragma warning restore 1591
